version: "3.7"
services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/traefik.yml"
  
  llm:
    image: ollama/ollama:latest
    container_name: llm
    profiles: ["linux"]
    ports:
      - 11434:11434
    volumes:
      - ./llm:/app
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.llm.rule=Host(`llm.${APP_DOMAIN_URL}`)"
      - "traefik.http.routers.llm.entrypoints=websecure"
      - "traefik.http.routers.llm.tls.certresolver=myresolver"
      - "traefik.http.services.llm.loadbalancer.server.port=11434"