version: "3.7"
services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--certificatesresolvers.myresolver.acme.email=${LETSENCRYPT_EMAIL}"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik/letsencrypt:/letsencrypt"
      - "./traefik/traefik.yml:/traefik.yml"